# Generated by Django 3.2.4 on 2021-06-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
    ]
