# Generated by Django 3.2.4 on 2021-06-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
    ]
